apiVersion: v1
kind: ConfigMap
metadata:
  name: consul
data:
  config.json: |-
    {
       "datacenter":"dc1",
       "primary_datacenter":"dc1",
       "server":true,
       "data_dir":"/consul/data",
       "log_level":"INFO",
       "node_name":"consul",
       "client_addr":"0.0.0.0",
       "ui_config":{
          "enabled":true
       },
       "telemetry":{
          "disable_compat_1.9":true
       },
       "acl":{
          "enabled":true,
          "default_policy":"deny",
          "enable_token_persistence":true,
          "tokens":{
             "initial_management":"d9828ae7-07c7-1c8a-de40-7152ee3964c2",
             "agent":"d9828ae7-07c7-1c8a-de40-7152ee3964c2"
          },
          "down_policy":"extend-cache"
       }
    }
  addr: "127.0.0.1:8500"
  token: "d9828ae7-07c7-1c8a-de40-7152ee3964c2"
