---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Values.deployment.metadata.name}}
    labels:
       env: {{.Values.deployment.metadata.labels.env}}
       author: Alexey-Medov
spec:
  replicas: {{.Values.deployment.spec.replicas}}
  selector:
    matchLabels:
      appname: {{.Values.deployment.spec.podLabel}}
  template:
    metadata:
      labels:
        appname: {{.Values.deployment.spec.podLabel}}
    spec:
      containers:
        - name : {{.Values.deployment.spec.container.name}}
          image: {{.Values.deployment.spec.container.image.name}}:{{.Values.deployment.spec.container.image.version}}
          ports:
            - containerPort: 8300
            - containerPort: 8500
          env:
            - name: CONSUL_HTTP_ADDR
              valueFrom:
                configMapKeyRef:
                  name: consul
                  key: addr
            - name: CONSUL_HTTP_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: consul
                  key: token 
            - name: CONSUL_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: consul
                  key: config.json
          command: ["/bin/sh"]
          args: ["-c", "echo $CONSUL_LOCAL_CONFIG > /consul/config/config.json; consul agent -server -bootstrap-expect=1 -data-dir=/consul/data -config-dir=/consul/config"]
