# Создаем Service с простым типом Cluster-IP для нашего деплоймента
---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
     author: Alexey-Medov
spec:
  type: ClusterIP
  selector:
    appname: consul                   # Говорим что будем отправлять трафик на Pod'ы у которых есть данная метка (label)
  ports:
    - name       : rpc-server
      protocol   : TCP
      port       : 8300               # Порт внутри-кластерного IP данного сервиса 
      targetPort : 8300               # Порт контейнера с микросервисом внутри пода (для nginx сервера например, это 80)
    - name       : http-api
      protocol   : TCP
      port       : 8500
      targetPort : 8500
