---
apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
     author: Alexey-Medov
spec:
  type: ClusterIP
  selector:
    appname: consul
  ports:
    - name       : rpc-server
      protocol   : TCP
      port       : 8300 
      targetPort : 8300
    - name       : http-api
      protocol   : TCP
      port       : 8500
      targetPort : 8500
