apiVersion: v1
kind: Pod
metadata:
  name: {{.Release.Name}}
spec:
  containers:
    - name : {{.Release.Name}}
      image: {{.Values.container.image_name}}:{{.Values.container.image_version}}
      ports:
        - containerPort: {{.Values.container.port}}
