apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: "user  nginx;\nworker_processes  auto;\n\nerror_log  /dev/stdout notice;\npid
    \       /var/run/nginx.pid;\n\n\nevents {\n    worker_connections  1024;\n}\n\nstream
    {\n\nupstream backend {\n    server 8.8.8.8:53;\n}\n\nlog_format proxy '[$time_local]
    $remote_addr '\n                 'protocol:$protocol  status:$status  bytes_sent:$bytes_sent
    \ bytes_received:$bytes_received  '\n                 'session_time:$session_time
    \ upstream_address:\"$upstream_addr\"  upstream_connect_time:\"$upstream_connect_time\"';\n\naccess_log
    /dev/stdout proxy buffer=4k flush=10s;\n\n    server {\n\tlisten 53;\n        proxy_connect_timeout
    60s;\n        proxy_timeout 300s;\n\tproxy_buffer_size 512k;\n        proxy_pass
    backend;\n    }\n\n}\n"
  
