apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{.Values.deployment.metadata.name}}               # Задаем имя деплоймента (из файла values)
    labels:
       env: {{.Values.deployment.metadata.labels.env}}
       author: Alexey-Medov
spec:
  replicas: {{.Values.deployment.spec.replicas}}             # Задаем количество реплик пода. То есть сколько экзепляров данного пода должно быть создано.
  selector:
    matchLabels:
      appname: example-1-pod                                 # Говорим что деплоймент будет связан с теми подами, у которых указан такой же Label.
  template:
    metadata:
      labels:
        appname: example-1-pod                               # Задаем имя пода
    spec:
      containers:
        - name : nginx                                       # Задаем имя первого контейнера
          image: nginx:latest                                # Указываем образ для первого контейнера
          ports:
            - containerPort: 80
            - containerPort: 443
        - name : redis                                       # Задаем имя второго контейнера
          image: redis:6.2.6                                 # Указываем образ для второго контейнера
          ports:
            - containerPort: 6379
