# Пример создания простого Job который под своим управлением будет запускать 2 одинаковых пода.
# При этом будем дейстовать ограничение, которое не даст запустить больше 1 пода за раз.
# Когда приложение внутри запущенного пода завершит свою работу успешно, под прекратит работу и затем запустится следующий под.
# Цель данного Job, выполнить в общей сложности успешный запуск 2 подов, чтобы каждый из 2 раз - успешно завершил свою работу.
# Но в нашем примере, поды будут останавливатся по истечению 30 секунд (если приложение в контейнере не успело выполнить свою работу - это его проблемы)

apiVersion: batch/v1
kind: Job
metadata:
  name: my-fourth-job-resourse
spec:
  activeDeadlineSeconds: 30                      # Время в секундах прошедших с момента запуска пода, которое дается для выполнения приложения внутри контейнера.
  completions: 2                                 # Сколько раз подряд должен запустится под с указанным контейнером и успешно завершится
  parallelism: 1                                 # Сколько подов паралельно будет разрешено выполнять за раз
  template:
    metadata:
      labels:
        type: test
    spec:
      restartPolicy: OnFailure                   # если контейнер завершится с ошибкой, Kubernetes перезапустит контейнер внутри того же пода.
      containers:
        - name: sleep1min
          image: medoff/sleep1min:latest
