# Пример создания простого Job который под своим управлением будет запускать 10 одинаковых подов.
# При этом будем дейстовать ограничение, которое не даст запустить больше 3 подов за раз.
# Когда приложение внутри запущенного пода завершит свою работу успешно, под прекратит работу и затем запустится следующий под.
# Цель данного Job, выполнить в общей сложности успешный запуск 10 подов, чтобы каждый из 10 раз - успешно завершил свою работу

apiVersion: batch/v1
kind: Job
metadata:
  name: my-first-job-resourse
spec:
  completions: 10                                 # Сколько раз подряд должен запустится под с указанным контейнером и успешно завершится
  parallelism: 3                                  # Сколько подов паралельно будет разрешено выполнять за раз
  template:
    metadata:
      labels:
        type: test
    spec:
      restartPolicy: OnFailure
      containers:
        - name: sleep1min
          image: medoff/sleep1min:latest
