# Этот манифест создаёт в Kubernetes задачу (Job), где запускает Pod с одним контейнером.
#
# Контейнер выполняет простую работу (имитирует выполнение в течение 1 минуты, например, sleep 60).
#
# После успешного завершения (код 0) Pod останавливается, но не удаляется — его можно посмотреть в списке Pod (статус Completed).
#
# Политика restartPolicy: OnFailure означает, что контейнер будет перезапущен только в случае ошибки, но не после успеха.

apiVersion: batch/v1
kind: Job
metadata:
  name: my-first-job-resource            # Имя нашего Job'a (задания)
spec:
  template:
    metadata:
      labels:
        env: test                        # Просто метка нашего пода (label)
    spec:
      restartPolicy: OnFailure           # Только если контейнер завершится с ошибкой, Kubernetes перезапустит контейнер внутри того же Pod.
      containers:
        - name: sleep1min
          image: medoff/sleep1min:latest
