# Пример создания простого Job который под своим управлением запустит 3 одинаковых пода подряд.
# То есть запускается первый Pod, он работает и успешно завершается, затем запускается новый под с тем же контейнером и тоже успешно завершается, и затем так еще один раз.
# После того как все 3 пода успешно отработали, поды останавливаются и переходят в статус Completed
# Естественно приложение внутри контейнера когда-нибудь должно будет завершится, чтобы создавался следующий по списку Pod.

apiVersion: batch/v1
kind: Job
metadata:
  name: my-second-job-resourse
spec:
  completions: 3                  # Сколько раз подряд будет создан такой под и завершится успешно. В нашем случае под будет запущен 3 раза подряд. То есть после остановки первого пода будет создано еще два раза.
  template:
    metadata:
      labels:
        type: test
    spec:
      restartPolicy: OnFailure    # если контейнер завершится с ошибкой, Kubernetes перезапустит контейнер внутри того же пода.
      containers:
        - name: sleep1min
          image: medoff/sleep1min:latest
