# Пример создания простого Job который под своим управлением запустит под, в котором будет запущен контейнер с таймером на 1 минуту, который по сути просто будет имитировать некую задачу.
# По истечении одной минут с момента запуска, таймер запущенный внутри контейнера прекратит свою работу и вернет код ответа 0, что значит что работа была успешно выполнена, под выключится (но не удалится).
# Job - это просто сервис, который следит за тем, чтобы был запущен некий под с контейнером внутри которого будет произведена некая работа и эта работа успешно выполнится.
# После успешного завершения работы (job) под будет остановлен, но не удален. Остановленные поды можно посмотреть командой kubectl get pods -a 

apiVersion: batch/v1
kind: Job
metadata:
  name: my-first-job-resource            # Имя нашего Job'a (задания)
spec:
  template:
    metadata:
      labels:
        env: test                        # Просто метка нашего пода (label)
    spec:
      restartPolicy: OnFailure           # Говорим что если контейнер прекратил работать(например упал), то автоматически он не перезапустится
      containers:
        - name: sleep1min
          image: medoff/sleep1min:latest
