apiVersion: v2                                         # Helm API Version
name: consul                                           # Helm Chart Name
version: 1.11                                          # Chart version
