deployment:
  metadata:
    name: consul
    labels:
      env: test
  spec:
    replicas: "1"
    podLabel: consul
    container:
      name: consul
      image:
        name: consul
        version: 1.11
