# Создаем Ingress который будет запросы маршрутизировать на наш Service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq
  annotations:
      nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: my.testsite.com
    http:
      paths:
      - path: /rabbitmq(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port: 
             number: 15672
