# Создаем Service с простым типом Cluster-IP для нашего деплоймента
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
     author: Alexey-Medov
spec:
  type: ClusterIP
  selector:
    appname: rabbitmq                # Говорим что будем отправлять трафик на Pod'ы у которых есть данная метка (label)
  ports:
    - name       : web-ui
      protocol   : TCP
      port       : 15672              # Порт внутри-кластерного IP данного сервиса 
      targetPort : 15672              # Порт контейнера с микросервисом внутри пода (для nginx сервера например, это 80)
    - name       : amqp
      protocol   : TCP
      port       : 5672
      targetPort : 5672
