---
#
# Просто создает Pod с HTTP Get проверкой (2xx,3xx) работоспособности 80 порта запущенного приложения Nginx  
# Перед первой проверкой работоспособности контейнера в поде, подождем 15 секунд, будем проверять каждый 10 секунды
# Время за которое должен быть получен ответ на запрос установим в 3 секунду
# Количество не удачных проверок подряд, после которых Pod будет считатся неработоспособным, установим в 2 
#
# В случае если все проверки подряд не прошли, то контейнер будет перезапущен.
#
apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
     env: test
spec:
  containers:
    - name : my-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
          scheme: HTTP
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 2
