---
# Создаем деплоймент

apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-backend-1-deployment      # Задаем имя деплоймента
    labels:
       env: test
       author: Alexey-Medov
spec:
  replicas: 3                        # Задаем количество реплик пода. То есть сколько экзепляров данного пода должно быть создано.
  selector:
    matchLabels:
      appname: my-backend-1            # Говорим что деплоймент будет связан с теми подами, у которых указан такой же Label.
  template:
    metadata: 
      labels:
        appname: my-backend-1          # Задаем имя пода
    spec:
      containers:
        - name : my-backend          # Задаем имя первого контейнера
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80

---
# Далее создаем сервис для нашего деплоймента

apiVersion: v1
kind: Service
metadata:
  name: my-backend-1-service
  labels:
     app: my-backend-1-deployment
spec: 
  selector:
    appname: my-backend-1              # Говорим что будем отправлять трафик на Pod'ы у которых есть данная метка (label)
  ports: 
    - name       : nginx
      protocol   : TCP
      port       : 80                # порт на балансере
      targetPort : 80                # Порт в Pod'e на который будет идти трафик
  type: LoadBalancer
