apiVersion: apps/v1
kind: Deployment
metadata:
    name: my-backend-deployment
    labels:
       env: test
       author: Alexey-Medov
spec:
  selector:
    matchLabels:
      appname: my-backend
  template:
    metadata: 
      labels:
        appname: my-backend                  # Pod name
    spec:
      containers:
        - name : nginx                       # First container specification
          image: nginx:latest                # -
          ports:                             # -
            - containerPort: 80              # -
            - containerPort: 443             # -
        - name : redis                       # Second container specification
          image: redis:6.2.5                 # --
          ports:                             # --
            - containerPort: 6379            # --
