apiVersion: v2                                         # Helm API Version
name: My Helm Chart With Deployment Example 1          # Helm Chart Name
version: 0.0.1                                         # 
appVersion: 6.2.6                                      # Application Version
