apiVersion: v2                            # (required) Helm API Version
name: Redis                               # (required) Helm Chart name
version: "6.2.6"                          # (required) Application Version in this Chart (Semantic Version)
appVersion: "6.2.6"                       # (not required, but recommended) Application Version in this Chart (Need not be Semantic Version)
description: My simple chart with Redis 
maintainers:                              # (optional)
     - name: Aleksey Medov                # (required for each maintainer) The maintainers name

