apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    env: dev
    app: nginx
    app: redis
spec:
  containers:
    - name : container-nginx
      image: nginx:latest
      ports: 
        - containerPort: 80
          protocol: TCP
    - name : container-redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
